### ISSUE TITLE
Show Popup in Mangol

### ISSUE THREAD

**Issue by jcendal** [fegyi001/mangol#12]
I tried to show popups with the coordinates on the mangol map when clicking but I could not. Do you know any way to do it?

**Comment by fegyi001** [comment]
Could you be more specific? E.g. code sample etc.

**Comment by jcendal** [comment]
yes sorry, i try to insert this example in my angular component with mangol map    http://openlayers.org/en/latest/examples/overlay.html  . Now i try insert it in container.component.ts.
![captura](https://user-images.githubusercontent.com/29627990/29613578-fb5df566-8806-11e7-874a-97c0a77f8bf1.JPG)

**Comment by fegyi001** [comment]
This is not an issue, just a simple use-case of Mangol which is quite doable.

But first of all, why do you use Mangol's source code instead of adding it as a dependency to your package.json? It is quite easy, just follow the Readme. Here I attach a working example solving your question. All you have to do is run ```npm install``` and then ```ng serve```.
[mangol-test.zip](https://github.com/fegyi001/mangol/files/1245285/mangol-test.zip)

For this to work I imported a couple of libs into the index.html (bootstrap & jquery, because the OpenLayers example was built using them), then by modifying the app.component.ts and the app.component.scss everything works as expected. 

Here is my result: 
![untitled](https://user-images.githubusercontent.com/4125222/29614857-1a379ac8-880c-11e7-8cde-6f3d080d4ea6.png)
