### ISSUE TITLE
Measured line length error

### ISSUE THREAD

**Issue by szoki-moki** [fegyi001/mangol#38]
Measure a line in Mangol and do the same in QGIS/Google Earth - the measurement in Mangol is much longer than in other softwares with the same projection.

**Comment by fegyi001** [comment]
@szoki-moki thanks for this issue. This was quite an interesting one. As it turned out the problem was that the drawed geometry's built-in ``getLength()`` and ``getArea()`` functions were not returning precise values at all. Instead of using the built-in functions I had to use the ``getArea(geom)`` and ``getLength(geom)`` functions of the ``ol/sphere`` class as it resulted the correct values. Weird.

There is a new version out now (9.1.10-0.3) or visit the demo page at http://188.166.116.137/mangol/#/demo-measure, you can try it and close the issue if it works for you.

**Comment by szoki-moki** [comment]
The measurement results are correct now, also for area and radius measurements. Thanks for the quick fix!
