### ISSUE TITLE
Some dependencies are deprecated

### ISSUE THREAD

**Issue by pmeems** [fegyi001/mangol#6]
I think Mangol uses these deprecated dependencies:

- npm WARN deprecated vector-tile@1.3.0: This module has moved: please install mapbox/vector-tile instead
- npm WARN deprecated point-geometry@0.0.0: This module has moved: please install mapbox/point-geometry instead

Would be good if the next version would use the newer dependencies.

**Comment by pmeems** [comment]
Some more compile warnings:
```
WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
Backtrace:
        node_modules/mangol/src/assets/scss/lib/neat/settings/_disable-warnings.scss:11, in mixin `-neat-warn`
        node_modules/mangol/src/assets/scss/lib/neat/grid/_row.scss:39, in mixin `row`
        node_modules/mangol/src/assets/scss/components/_sidebar.scss:9
```

```
WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
Backtrace:
        node_modules/mangol/src/assets/scss/lib/neat/settings/_disable-warnings.scss:11, in mixin `-neat-warn`
        node_modules/mangol/src/assets/scss/lib/neat/grid/_row.scss:39, in mixin `row`
        node_modules/mangol/src/assets/scss/components/_layertree.scss:58
```

**Comment by fegyi001** [comment]
Yes, the neat library is deprecated. In the future I intend to upgrade it to its new version (or completely omit  ), but since it is completely rewritten it is not trivial. But I don't think that's an issue, only an annoying warning, Mangol works fine with the deprecated neat version. 

The other deprecated libraries are not Mangol-specific. I updated OpenLayers to 4.2.0, these warnings are fixed there.
